#!/usr/bin/env bash

COL_GREEN="\e[1;32m"
COL_NORMAL="\e[m"

err() {
    echo -e "$1" >&2
    exit 1
}

usage() {
    echo -e "Usage: ${0##*\/} [-k | -u] [-h] [device_node]" >&2
}

if [ $UID -ne 0 ]; then
    err "only root can do that"
fi

OPTS=`getopt -o kuh? -l help -l kernel-only -l uboot-only -- "$@"`
if [ "$?" != 0 ]; then
    usage
    exit 1
fi

eval set -- "$OPTS"

while true; do
    case "$1" in
        -h|--help|?)
            usage
            exit 0
            ;;
        -k|--kernel-only)
            UPLOAD_KERNEL_ONLY=1
            shift
            ;;
        -u|--uboot-only)
            UPLOAD_UBOOT_ONLY=1
            shift
            ;;
        --)
            shift; break;;
    esac
done

if [ $# -eq 0 ]; then
    echo -en "${COL_GREEN}Please input the device node of the card (e.g. /dev/sdb):${COL_NORMAL} "
    read devnode
else
    devnode="$1"
fi

if [ `echo $devnode | grep "[0-9]$"` ] ; then
    err "Error: please specify a whole disk instead of a partition."
fi

if ! [ -b $devnode ] ; then
    err "Error: $devnode does not exist."
fi

if [[ "$2" == "pistachio" ]]; then
  DEVICE="pistachio"
  DTB_TARGET='imx6q-pistachio.dtb'
fi

upload_kernel() {
    mkdir sdcard 2>/dev/null
    mount ${devnode}1 sdcard
    echo -e "\n${COL_GREEN}--${COL_NORMAL}"
    echo -e "${COL_GREEN}Flashing zImage and dtb files to ${devnode}...${COL_NORMAL}"
    cp -rv uboot-imx/board/nutsboard/${DEVICE}/uEnv.txt sdcard/uEnv.txt
    cp -rv linux-imx/arch/arm/boot/zImage sdcard/
    cp -rv linux-imx/arch/arm/boot/dts/"$DTB_TARGET" sdcard/
    umount sdcard 2>/dev/null

    echo -e "\n${COL_GREEN}--${COL_NORMAL}"
    echo -e "${COL_GREEN}Flashing k-modules to ${devnode}...${COL_NORMAL}"

    mount ${devnode}2 sdcard 2>/dev/null
    mkdir -p sdcard/lib/modules/
    cp -rv linux-imx/modules/lib/modules/* sdcard/lib/modules/
    umount sdcard 2>/dev/null
    rm -rf sdcard 2>/dev/null
}

upload_uboot() {
    echo -e "\n${COL_GREEN}--${COL_NORMAL}"
    echo -e "${COL_GREEN}Flashing u-boot.imx to ${devnode}...${COL_NORMAL}"
    dd if=uboot-imx/u-boot.imx of=${devnode} bs=1K seek=1;sync;
}

ishdd=0
for b in /dev/disk/by-id/* ; do
    echo $b | grep HARDDISK >/dev/null || continue
    ls -l $b | grep "${devnode##*/}$" >/dev/null && ishdd=1 && break
done
if [ $ishdd -ne "0" ] ; then
    echo -en "${COL_GREEN}${devnode} is a hard drive. Continue [y/N]?${COL_NORMAL} "
    read ans
    echo $ans | grep -i "y" > /dev/null || err "Interrupted by user."
fi

echo -en "${COL_GREEN}Things on ${devnode} may probably be erased. Continue [y/N]?${COL_NORMAL} "
read ans
echo $ans | grep -i "y" > /dev/null || err "Interrupted by user."

echo -e "\n${COL_GREEN}--${COL_NORMAL}"
echo -e "${COL_GREEN}Unmounting all mounted partition on ${devnode}...${COL_NORMAL}"
mount | grep "^$devnode" | awk '{print $3}' | while read mpoint ; do
    umount $mpoint
done

if [ $UPLOAD_KERNEL_ONLY ]; then
    upload_kernel
    exit $?
fi

if [ $UPLOAD_UBOOT_ONLY ]; then
    upload_uboot
    exit $?
fi

echo -e "\n${COL_GREEN}--${COL_NORMAL}"
echo -e "${COL_GREEN}Deleting partition table on ${devnode}...${COL_NORMAL}"
dd if=/dev/zero of=${devnode} bs=512 count=4096 conv=fsync
dd if=/dev/zero of=${devnode} bs=512 count=4096 conv=fsync seek=$((`blockdev --getsz ${devnode}` - 4096))
partprobe

echo -e "\n${COL_GREEN}--${COL_NORMAL}"
echo -e "${COL_GREEN}Manipulating partiton table on ${devnode}...${COL_NORMAL}"
(echo n; echo p; echo 1; echo 2048; echo 34815; echo n; echo p; echo 2; echo; echo; echo w;) | fdisk ${devnode}

echo -e "\n${COL_GREEN}--${COL_NORMAL}"
echo -e "${COL_GREEN}Creating filesystem on ${devnode}1...${COL_NORMAL}"
mkfs.fat -F 32 ${devnode}1
mkfs.ext4 ${devnode}2

echo -e "\n${COL_GREEN}--${COL_NORMAL}"
echo -e "${COL_GREEN}Mounting ${devnode}1 on sdcard/...${COL_NORMAL}"
mkdir sdcard 2>/dev/null
mount ${devnode}2 sdcard

echo -e "\n${COL_GREEN}--${COL_NORMAL}"
echo -e "${COL_GREEN}Copying rootfs to sdcard/...${COL_NORMAL}"
cd sdcard
tar --numeric-owner -xzvf ../oneiric.tgz
cd -

echo -e "\n${COL_GREEN}--${COL_NORMAL}"
echo -e "${COL_GREEN}Unmounting sdcard/...${COL_NORMAL}"

umount sdcard 2>/dev/null
rm -rf sdcard 2>/dev/null

upload_uboot;sync;
upload_kernel;sync;

echo -e "\n${COL_GREEN}Done.${COL_NORMAL}"
